[package]
name = "greengait_solana"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-client = "0.30.1"
anchor-lang = "0.30.1"
solana-sdk = "1.18.14"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
spl-token = "4.0.0"
